### ISSUE TITLE
Slow invoking on Android client

### ISSUE THREAD

**Issue by blackspiritus** [erizet/SignalA#11]
Hi,

I am using your library for an Android app. When I get data on my Android app from my SignalR server invoked from a C# form, the data comes almost instantly. But when I send data from my Android client to my SignalR server, it takes a while before the server gets the data. Now I can't seem to find any solution for it. Do you know any solution? I have also a website that can communicate with the server and this works perfectly.

Regards,
Gillan

**Comment by inventde** [comment]
erizet i love this library and it works perfect for my project, but the only issue i'm having is that my application crashes when i'm offline. how can i resolve this issue?

**Comment by erizet** [comment]
First of all, please open a new issue. Then if possible include a stacktrace.
