### ISSUE TITLE
Reconnecting problem

### ISSUE THREAD

**Issue by gksource** [erizet/SignalA#29]
First of all I would like to thank you for your great work with SignalR.

After couple of minutes not interacting with SignalR server my app goes in to Reconnecting State and stays there it never connects any more, after some debugging I'm getting this exceptions first java.io.EOFException and after that java.net.SocketTimeoutException and my app after this never connects to SignalR server.
Can you please help me with this.
Thank you.

**Comment by xjpmauricio** [comment]
I'm having the same issue. It's quite simple to reproduce: connect to a hub, shutdown the server (in my case iis), this is the sequence of events triggered on the HubConnection events:
- OnError: java.lang.Exception: Error when calling endpoint.
- Reconnecting
- OnError: com.turbomanage.httpclient.HttpRequestException: java.net.SocketTimeoutException: connect timed out

After that, it doesn't try to reconnect any more. Any ideas?
