### ISSUE TITLE
Restart connection issue

### ISSUE THREAD

**Issue by matskr90** [erizet/SignalA#36]
Hello, thank you for the great library. I use your library in my thesis. I'm writting application for vehicle tracking, but my code is similar to hubgroupdemo. I have one problem with stop connection. When I calling method "connection.Stop()" I get error: "DisconnectingState - Clean disconnect failed. 200" and I can't restart connection. I tested also hubgroupdemo and is the same issue. Until restart activity (calling onDestroy) I can't reconnect to the hub. Is the possibility to close connection and start again without exit app?

Additional information:
phone - nexus 4 with android 4.4.2
server - SignalR 2.0.1
library version - latest (v15)

Thx in advance for any reply, it's very important to me

---------EDIT----------------

My fault, it's works now.

**Comment by Narinc** [comment]
is there any one? I am struck, too.
