### ISSUE TITLE
How to authenticate when working with WebApi

### ISSUE THREAD

**Issue by katzdan** [erizet/SignalA#9]
Hi Erik,

I am testing your lib and considering using it when you release version 1.0. It looks very promising and I hope it will help me reduce network calls in an Android application I am working on. Respect.

My question is - how should I authenticate when working with my .Net serverv side WebApi ? The app authenticated using Basic authentication (an "Authentication" header with the username & password encoded in Base64) over a SSL connection. WebApi means no Session info and no Forms authentication info, only Identity information which is re-crated on every call based on the provided authentication header.

I want to initiate the connection somehow but can't figure out how to do it. there is no way to add headers to the requests and i'm not sure SignalA knows how to communicate over SSL  (accepting a SSLSocketFactory object or a similar method).

Any suggestions?

Regards,
Dan

**Comment by YasserMojahed** [comment]
is there any news here?
